### PR TITLE
Add identifiers

### PR DESCRIPTION
**Pull request by BerniVarga**

### CODE REVIEW

**Comment by tosan88** [comment]
:+1:

**Comment by catalin-ilea** [comment]
lgtm

**Comment by dawngerpony** [comment]
FYI the corresponding PR for public-people-api is here: 
https://github.com/Financial-Times/public-people-api/pull/6

**Comment by dawngerpony** [comment]
@BerniVarga / @sjwells - FYI I have merged Sarah's changes for extra fields from `master` into this branch, but the tests aren't quite passing yet. I figured it would be better to commit this change because it will hopefully save time, rather than it being wasted work. I think the amount of extra work required to get tests passing should be minimal.

**Comment by BerniVarga** [comment]
@duffj Could you do the merge on a separate branch next time, please? We have a process of creating a separate PR in cases like this. It's pretty hard to see the merge changes here, also, we had a clean PR - which now needs to be fixed. Thanks. :)

**Comment by nwrigh** [comment]
:+1:

**Comment by tosan88** [comment]
:+1:

**Pull request merged**
