### PR TITLE
Calculate hash on write - FOR DISCUSSION - DO NOT MERGE YET

### PR DESCRIPTION
**Pull request by ghost**
This uses a 128 bit murmur3 hash of the incoming json (normalised). The hash
value is a hex encoded string of the resulting hashed bytes.

Normalised means encoded to json with the fields in the order specified
in the corresponsing struct, with no superfluous whitespace and no newlines
or carriage returns.

Note that this would be fragile against:
- re-ordering of fields in the struct
- adding new fields (which we'd expect to change the hash anyway)

but is robust against:
- being called with the fields in any order
- being called with any mix of whitespace, newlines, etc.

Once tweaked and agreed, it's likely the hashing code will move
somewhere shared.

### CODE REVIEW

**Comment by dgem** [comment]
Nice compact code change :)

Is it worth doing a sort on the json structure to avoid the 'order in struct' sensitivity ?
It seems to rely on the way in which encoding/json in Go works, do we need to consider / check Java checksums?
I guess it depends on whether we'd need to be sure that the X in neo4j is the same one as in MongoDB (since currently one writer is in Java and the other in Go)

**Comment by ghost** [comment]
I did think of sorting, but it adds quite a bit of complexity to the code (unless someone can think of a better way to do it than I can) and we'd need to measure cpu impact too.

I don't think it's go specific, but it does mean being able to configure the serialiser to honour the ordering in the structs/classes and to omit whitespace and newlines.  I hope we can do that in java, but it needs testing.  We should also test that we get the exact same hash outputs in the java case.

I think we do want the same in mongo/neo4j/elasticsearch etc if it's easy to achieve, and I think it is.  My existing dump/restore tools would benefit enormously from that I think, with very minor modifications.

Anyone fancy doing the equivalent in java in document store api as a test?

**Comment by kghatton** [comment]
I'd like to take up the task of a Java implementation, there's support in Guava so it shouldn't be difficult - other than finding the time ...

Like @dgem I prefer the idea of a canonical (alphabetical) ordering of fields - this would be impervious to reordering in the JSON or in any struct (and also removes any requirement to mirror field ordering between Go and Java implementations).

**Comment by ghost** [comment]
I think I prefer it too, cost and complexity being equal, but they are not.  The question is whether it's worth the cost.  We may have to implement it, review, and measure before we can decide.

**Comment by kghatton** [comment]
Field order is not guaranteed in Java: https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getFields--

"... The elements in the returned array are not sorted and are not in any particular order."

**Comment by ghost** [comment]
So how do java serialisers manage to return fields in the "right" order typically?

**Comment by kghatton** [comment]
Object serialization: The class definition in the stream declares the fields in the order they will be written.
JSON serialization: Is either random, or controlled by the Jackson JsonPropertyOrder annotation.

**Comment by ghost** [comment]
Updated to use different json encoding to achieve alpha ordering of properties. (which, from previous experience also tends to be faster than the stdlib one, although I haven't measured yet)

**Pull request closed without merging**
