### PR TITLE
Simpler cypher

### PR DESCRIPTION
**Pull request by ghost**
Loading all people locally takes ages for me these days.  These changes make it noticeably faster.

Please review queries for correctness.

If people are happy, these minor changes can also be made in other r/w apps.

### CODE REVIEW

**Comment by nwrigh** [comment]
:+1:  Looks good and very obvious when in front of you .

**Comment by BerniVarga** [comment]
+1 yes, it's much simpler. we should adopt it in the other writers too...

**Comment by ghost** [comment]
Anyone want to do any further testing of any kind before I merge? (the tests pass)

**Comment by nwrigh** [comment]
We normally get Derek to test it in an environment before merging. So can you tag the branch and push it to semantic please?

**Comment by tosan88** [comment]
:+1:

**Comment by nwrigh** [comment]
Implemented in another pull request: https://github.com/Financial-Times/people-rw-neo4j/pull/29

**Pull request closed without merging**
